### ISSUE TITLE
[SDK-CORE BUG] Serialization Error

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1034]
**Describe the bug:**
A clear and concise description of what the bug is. What feature are you experiencing the bug with?

Has anyone gotten this error like this while using the sf sdk? Im getting this in test trying to execute a transaction:
 
 ```    TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'SourceFile'
    |     property 'contracts' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Contract'
    |     property 'location' -> object with constructor 'SourceLocation'
    --- property 'file' closes the circle
      at JSON.stringify (<anonymous>)
      at new SFError (node_modules/@superfluid-finance/sdk-core/src/SFError.ts:56:27)
      at Operation.exec (node_modules/@superfluid-finance/sdk-core/src/Operation.ts:45:19)
      at async Context.<anonymous> (test/REXTwoWayAlluoMarket.test.ts:623:13)
```

Looked at SFError.ts:56 and found this code (https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/src/SFError.ts#L50):
```
// NOTE: this is a temporary solution to fix serializeError
// which throws a weird JSON error
const stringifyCause = (cause?: Error | unknown) => {
    try {
        return JSON.stringify(serializeError(cause), null, 2);
    } catch (err) {
        return JSON.stringify(cause, null, 2); // line 56 where the error is
    }
};
```
I think there might still be some serialize errors coming through

**Comment by mikeghen** [comment]
I would just not stringify the error, console.log() it fixed this for me, at least it let me see the actual error which looks like a revert when opening the stream
