### ISSUE TITLE
[SDK-CORE][BUG] SDK fails to initialize using forking

### ISSUE THREAD

**Issue by mikeghen** [superfluid-finance/protocol-monorepo#1695]
**Describe the bug:**
During fork testing, I ran into this error:
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at getAddressesData (/Users/mghen/Documents/Projects/dca-pro-core/node_modules/@superfluid-finance/sdk-core/src/constants.ts:40:26)
    at /Users/mghen/Documents/Projects/dca-pro-core/node_modules/@superfluid-finance/sdk-core/src/constants.ts:51:46
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/mghen/Documents/Projects/dca-pro-core/node_modules/@superfluid-finance/sdk-core/src/constants.ts:51:23)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```

This is because of this note here: https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/src/constants.ts#L43

While this "should never happen," in some cases it does and the SDK will break on this line here: https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/src/constants.ts#L48

I believe this is the result of using a forking method which has a chainId that's not in your config. Hardcoding `chainId = 137` fixes the issue.

**Comment by 0xdavinchee** [comment]
hey @mikeghen thank you for reporting this issue, it seems like you've found a solution to the issue. 
What sort of fix are you exactly looking for? A better comment for debugging (a comment mentioning your solution).

Honestly, not sure what happened here because if the chainId did not exist it should've [returned null](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/sdk-core/src/constants.ts#L37).

Instead, subgraphEndpoint turned out to be undefined somehow here.

**Comment by hellwolf** [comment]
closing outdated issues.
