### ISSUE TITLE
[TOOLING] [BUG] lerna complains, can't parse yarn.lock

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1899]
Occuring in nix shell, at commit 6001337dc46da637269b24aaf0b93c8929d75ccc
```
$ yarn show-versions
yarn run v1.22.19
$ lerna ls --long
lerna notice cli v7.4.2

 >  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Target project does not exist: npm:ethereumjs-abi@0.6.8


   Error: Target project does not exist: npm:ethereumjs-abi@0.6.8
    at validateCommonDependencyRules (/home/didi/src/sf/protocol-monorepo/node_modules/nx/src/project-graph/project-graph-builder.js:285:15)
    at validateDependency (/home/didi/src/sf/protocol-monorepo/node_modules/nx/src/project-graph/project-graph-builder.js:275:5)
    at ProjectGraphBuilder.addDependency (/home/didi/src/sf/protocol-monorepo/node_modules/nx/src/project-graph/project-graph-builder.js:162:9)
    at ProjectGraphBuilder.addStaticDependency (/home/didi/src/sf/protocol-monorepo/node_modules/nx/src/project-graph/project-graph-builder.js:79:14)
    at /home/didi/src/sf/protocol-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:182:41
    at Array.forEach (<anonymous>)
    at /home/didi/src/sf/protocol-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:178:49
    at Array.forEach (<anonymous>)
    at /home/didi/src/sf/protocol-monorepo/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:176:72
    at Array.forEach (<anonymous>)

lerna info versioning independent
autowrap                                     v0.0.1 packages/automation-contracts/autowrap
scheduler                                    v0.0.1 packages/automation-contracts/scheduler
@superfluid-finance/ethereum-contracts       v1.9.1 packages/ethereum-contracts
@superfluid-finance/hot-fuzz                 v0.1.0 packages/hot-fuzz
@superfluid-finance/js-sdk                   v0.6.3 packages/js-sdk
@superfluid-finance/metadata                v1.1.28 packages/metadata
@superfluid-finance/sdk-core                v0.6.13 packages/sdk-core
@superfluid-finance/sdk-redux                v0.5.1 packages/sdk-redux
@superfluid-finance/solidity-semantic-money  v0.1.0 packages/solidity-semantic-money
@superfluid-finance/subgraph                 v1.7.0 packages/subgraph
lerna success found 10 packages
Done in 1.65s.
```
Investigating:
```
didi@P1G4:~/src/sf/protocol-monorepo$ git grep ethereumjs-abi
yarn.lock:    ethereumjs-abi "^0.6.8"
yarn.lock:    ethereumjs-abi "git+https://github.com/ethereumjs/ethereumjs-abi.git"
yarn.lock:ethereumjs-abi@^0.6.8:
yarn.lock:  resolved "https://registry.yarnpkg.com/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz#71bc152db099f70e62f108b7cdfca1b362c6fcae"
yarn.lock:"ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git":
yarn.lock:  resolved "git+https://github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"
yarn.lock:    ethereumjs-abi "^0.6.8"
didi@P1G4:~/src/sf/protocol-monorepo$ yarn why ethereumjs-abi
yarn why v1.22.19
[1/4] Why do we have the module "ethereumjs-abi"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ethereumjs-abi@0.6.8"
info Reasons this module exists
   - "_project_#hardhat" depends on it
   - Hoisted from "_project_#hardhat#ethereumjs-abi"
   - Hoisted from "_project_#@truffle#hdwallet-provider#@metamask#eth-sig-util#ethereumjs-abi"
info Disk size without dependencies: "484KB"
info Disk size with unique dependencies: "1.08MB"
info Disk size with transitive dependencies: "13.02MB"
info Number of shared dependencies: 33
=> Found "eth-sig-util#ethereumjs-abi@0.6.8"
info This module exists because "_project_#@truffle#hdwallet-provider#web3-provider-engine#eth-sig-util" depends on it.
info Disk size without dependencies: "344KB"
info Disk size with unique dependencies: "968KB"
info Disk size with transitive dependencies: "12.88MB"
info Number of shared dependencies: 33
Done in 1.10s.
```

**Comment by hellwolf** [comment]
The information about severity is not complete. I am assigning a low severity according to my best judgment without relevant information.

**Comment by hellwolf** [comment]
Per Didi: after cleaning up cache, it was fixed.
