### ISSUE TITLE
Module not found `../abi`

### ISSUE THREAD

**Issue by santisiri** [superfluid-finance/protocol-monorepo#230]
Following tutorial here: https://docs.superfluid.finance/superfluid/protocol-tutorials/setup-local-environment.

This line on loadContract.js is not resolving: 

```
const abis = require("../abi");
```

Do I need to setup anything on `js-sdk` first?

I'm getting this when trying: `SuperfluidSDK = require("@superfluid-finance/js-sdk")`:

```
Uncaught Error: Cannot find module '../abi'
Require stack:
- /Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/utils/loadContracts.js
- /Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/Framework.js
- /Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/utils/loadContracts.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/Framework.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at evalmachine.<anonymous>:0:17
    at sigintHandlersWrap (vm.js:278:15)
    at Script.runInContext (vm.js:139:14)
    at runScript (/Users/santisiri/Ethereum/ethereum-contracts/node_modules/truffle/build/webpack:/packages/core/lib/console.js:251:1)
    at Console.interpret (/Users/santisiri/Ethereum/ethereum-contracts/node_modules/truffle/build/webpack:/packages/core/lib/console.js:266:1)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
    at REPLServer.onLine (repl.js:809:10)
    at REPLServer.emit (events.js:314:20)
    at REPLServer.EventEmitter.emit (domain.js:486:12)
    at REPLServer.Interface._onLine (readline.js:337:10)
    at REPLServer.Interface._line (readline.js:666:8)
    at REPLServer.Interface._ttyWrite (readline.js:1010:14)
    at REPLServer.self._ttyWrite (repl.js:899:9)
    at ReadStream.onkeypress (readline.js:213:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/utils/loadContracts.js',
    '/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/Framework.js',
    '/Users/santisiri/Ethereum/ethereum-contracts/packages/js-sdk/src/index.js',
    '<repl>'
  ]
}
```

**Comment by pi0neerpat** [comment]
Posting our convo from Discord here

Ran `yarn install` and `yarn build` in the ROOT of the repo will fix this.
